micronaut:
  application:
    name: mn04


datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb


netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
